name: Reusable Deploy
on: 
    workflow_call:
        inputs:
            artifact-name:
                description: The name of the deployable artifact
                required: true
                default: dist
                type: string
jobs:
    deploy:
        runs-on: ubnuntu-latest
        steps:
            - name: Get code
              uses: actions/download-artfact@v3
              with:
                name: ${{ inputs.artifact-name }}
            - name: List files
              run: ls
            - name: Deploying
              run: echo "Deploying & uploading..."